### PR TITLE
Created PR to the lang pt

### PR DESCRIPTION
**Pull request by brunommpreto**
Fixed typo in the README file
Added maintainers for the Portuguese(pt) language

### CODE REVIEW

**Comment by brunommpreto** [comment]
The other maintainer is Brazilian should we do it "pt.json" or "pt-br.json".
The doubt came from a previous [comment](https://github.com/ethereum/solidity/issues/10119#issuecomment-720503348) on the issue ['#10119'](https://github.com/ethereum/solidity/issues/10119)

**Comment by franzihei** [comment]
Hi @brunommpreto,
Sorry for the late reply, for some reason I didn't get notified or didn't see this. :(
I think it's fine to go with `pt.json` for now. Let me know if you have any questions in the process.

**Comment by brunommpreto** [comment]
@franzihei I am not able to create a repo within the https://github.com/solidity-docs organization, can you double-check the permissions?

**Comment by franzihei** [comment]
You should be able to do so now, can you try again @brunommpreto ?

**Comment by brunommpreto** [comment]
@franzihei  I'm still unable to do so
https://i.imgur.com/TUGSvf9.png

The idea is to create another repo within the 'organization' in https://github.com/solidity-docs right? Because that I can't do. I don't have the option to create a new repository. perhaps you can create a new repo within the organization and add me there. 

I mean, from what I understood I should create a repo named pt-portuguese within the organization 'solidity-docs' if it is something else, let me know

**Comment by franzihei** [comment]
I also created this thread in case more coordination is needed: https://forum.soliditylang.org/t/translations-portuguese-coordination-thread/426

**Comment by brunommpreto** [comment]
@franzihei did you read the previous message?

**Pull request merged**
